config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :models
  resources :contacts
  get 'home/contacts'
  get 'home/addcontacts'

  root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    belongs_to :user
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
   # @contact = Contact.new
   @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    # @contact = Contact.new(contact_params)
   @contact = current_user.contacts.build(contact_params)


    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not authorized to edit this contact." if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email, :u_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contacts
  end

  def addcontacts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name%>
    <%= f.text_field :name , class:"form-control"%>
  </div><br>
  <div class="field form-group">
    <%= f.label :phone  %>
    <%= f.text_field :phone , class:"form-control"%>
  </div><br>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email , class:"form-control"%>
  </div><br><br>
  <div class="field form-group">
       <%= f.number_field :user_id , id: :contact_user_id , value: current_user.id , class:"form-control" , type: :hidden%>
  </div><br>

  <div class="actions">
    <%= f.submit  class:"btn btn-primary" %>
  </div><br>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<table class="table table-success table-striped">
<thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @contacts.each do |contact| %>
      <% if contact.user == current_user%>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
  
</table>


<%= link_to 'New Contact', new_contact_path, class: "btn btn-outline-primary" %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="card text-center">
  <div class="card-header">
  <%= @contact.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @contact.phone %></h5>
    <p class="card-text"> <%= @contact.email %></p>
    <%= link_to 'Edit Contact',  edit_contact_path(@contact) , class: "btn btn-outline-primary" %>
    <%= link_to 'Back to Contacts',  contacts_path , class: "btn btn-outline-primary" %>

  </div>
  </div>

app/views/home/_footer.html.erb
<div class="footer">
  <p>These are the contacts of mine.</p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Home", root_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in?%>

        <li class="nav-item">
        <%= link_to "Home", contacts_path, class:"nav-link" %>
          
        </li>
        <li class="nav-item">
        <%= link_to "Add Contacts", new_contact_path, class:"nav-link" %>

        </li>

                    
        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>

       </li>

        <li class="nav-item">
       <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>

       </li>

       <% else %>

        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>

        </li>

        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>

        </li>

        <% end %>
      
        </ul>
     
    </div>
  </div>
</nav>

app/views/home/contacts.html.erb
<h1>Contacts</h1>

app/views/home/index.html.erb
<div style="text-align: center;">
<h1>Welcome to My Contacts</h1>   

<img src="../assets/contacts.jpg"  width="500" height="500">


</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Contacts</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= render '/home/header' %>
  <div class ="container">

  <br/> 
  <% if notice %>
    <%= render 'layouts/alerts'%>
    <% end %>
  
  <%= yield %>
  </div>
  <%= render '/home/footer' %>
  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pages/home.html.erb
<div class="main">
  <div class="container">
    <h1>Hello my name is Shihara</h1>
    <p>I make Rails apps.</p>
  </div>
</div>